[package]
name = "shared_types"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]

[build-dependencies]
anyhow.workspace = true
crux_core = { path = "../../../crux_core", features = ["typegen"] }
crux_http = { path = "../../../crux_http" }
crux_kv = { path = "../../../crux_kv" }
crux_platform = { path = "../../../crux_platform" }
crux_time = { path = "../../../crux_time" }
shared = { path = "../shared" }
