[workspace]
members = [
  "crux_core",
  "crux_http",
  "crux_kv",
  "crux_macros",
  "crux_platform",
  "crux_time"
]

[workspace.package]
authors = ["Red Badger Consulting Limited"]
edition = "2021"
repository = "https://github.com/redb